### PR TITLE
Create a multiarch image

### PR DESCRIPTION
**Pull request by johngmyers**
This is an attempt to address #89.

I don't have gcloud credentials, so cannot test.

### CODE REVIEW

**Comment by MrHohn** [comment]
Sorry that I missed this. Thanks and I will try to test this and get back today.

**Comment by hakman** [comment]
Thanks @MrHohn !

**Comment by MrHohn** [comment]
Sorry for the delay, I tried to run this locally and hit the below error:
```
docker manifest create gcr.io/zihongz-k8s-dev/cluster-proportional-autoscaler:1.8.1-dirty --amend gcr.io/zihongz-k8s-dev/cluster-proportional-autoscaler-amd64:1.8.1-dirty --amend gcr.io/zihongz-k8s-dev/cluster-proportional-autoscaler-arm:1.8.1-dirty --amend gcr.io/zihongz-k8s-dev/cluster-proportional-autoscaler-arm64:1.8.1-dirty --amend gcr.io/zihongz-k8s-dev/cluster-proportional-autoscaler-ppc64le:1.8.1-dirty
docker manifest create is only supported on a Docker cli with experimental cli features enabled
make: *** [Makefile:109: multiarch-container] Error 1
```

Any prerequisite on the docker CLI configuration?

**Comment by MrHohn** [comment]
Okay, I was able to run it with `"experimental": "enabled"` set in docker config.

Looks like this is working fine - gcr.io/zihongz-k8s-dev/cluster-proportional-autoscaler:1.8.1-dirty for example.

**Comment by hakman** [comment]
@MrHohn you could add `DOCKER_CLI_EXPERIMENTAL=enabled` in front of the new Docker commands or export it in the beginning of the Makefile.
```bash
DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create $(MULTIARCH_IMAGE):$(VERSION) \
    $(addprefix --amend $(REGISTRY)/$(BIN)-, $(addsuffix :$(VERSION), $(ALL_ARCH)))
```

**Comment by johngmyers** [comment]
@MrHohn could we get a release cut with this PR in it?

**Comment by MrHohn** [comment]
@johngmyers Sorry for the delay - sure thing, let's track the release on https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/issues/89.

**Pull request merged**
