### PR TITLE
Bump golang version to 1.19.

### PR DESCRIPTION
**Pull request by MrHohn**
- Fix a gofmt error to pass the test.

Ref https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/issues/131.

### CODE REVIEW

**Comment by jingyuanliang** [comment]
Do we also need to bump the version number(s) in go.mod?

**Comment by MrHohn** [comment]
> Do we also need to bump the version number(s) in go.mod?

Thanks! Updated now.

**Comment by MrHohn** [comment]
Thanks! Merging per the lgtm.

**Pull request merged**
