### PR TITLE
Update go dependencies

### PR DESCRIPTION
**Pull request by MrFreezeex**
This PR updates go dependencies and go version.

### CODE REVIEW

**Comment by MrFreezeex** [comment]
I actually did this because on our cluster with kubernetes 1.25 and min tls version (with k8s.gcr.io/cpa/cluster-proportional-autoscaler-amd64:1.8.5) we encountered the following error: `github.com/kubernetes-incubator/cluster-proportional-autoscaler/pkg/autoscaler/k8sclient/k8sclient.go:96: Failed to list *v1.Node: Get https://10.233.0.1:443/api/v1/nodes: remote error: tls: protocol version not supported`, tested this new version with version updated and worked fine on my end.

**Review by MrHohn — COMMENTED** [review]
@MrFreezeex Thanks for the PR, I'm inclined to merge this PR and revert mine on https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/pull/136 as yours updated the go dependencies as well.

Would you mind updating the go version in go.mod file as well as pining the golangci-lint version to v1.51.2 in the build/lint.sh file (to workaround a known bug with golang1.20 and golangci-lint: https://github.com/golangci/golangci-lint/issues/3565)? Thanks.

**Comment by MrFreezeex** [comment]
> @MrFreezeex Thanks for the PR, I'm inclined to merge this PR and revert mine on #136 as yours updated the go dependencies as well.
> 
> Would you mind updating the go version in go.mod file as well as pining the golangci-lint version to v1.51.2 in the build/lint.sh file (to workaround a known bug with golang1.20 and golangci-lint: [golangci/golangci-lint#3565](https://github.com/golangci/golangci-lint/issues/3565))? Thanks.

Hey @MrHohn, thanks for the feedback, I cherry-picked your commit in this PR and dropped mine. Feel free to either merge your PR or merge this one that include your commit :D.

**Comment by jingyuanliang** [comment]
I don't think we need to pin it in lint.sh. Compare to netd impl where there's a lint Github action.

**Comment by MrFreezeex** [comment]
> I don't think we need to pin it in lint.sh. Compare to netd impl where there's a lint Github action.

Yeah sure done :+1:, it's the latest version anyway so it should not change much as of right now anyway.

**Review by MrHohn — APPROVED** [review]
Thanks!
/lgtm
/approve

**Pull request merged**
